create table machine_state (id tinyint unsigned not null auto_increment, state varchar(16) not null, primary key(id));
create table machine_substate (id tinyint unsigned not null auto_increment, state varchar(16) not null, primary key(id));
create table boot_device (id tinyint unsigned not null auto_increment, name varchar(16) not null, primary key(id));
create table nic_driver (id tinyint unsigned not null auto_increment, name varchar(16) not null, primary key(id));
insert into machine_state (state) values('halted');
insert into machine_state (state) values('booting');
insert into machine_state (state) values('running');
insert into machine_state (state) values('halting');
insert into machine_state (state) values('rebooting');
insert into machine_state (state) values('snapshotting');
insert into machine_state (state) values('reverting');
insert into machine_state (state) values('migrating');
insert into machine_state (state) values('failing over');
insert into machine_state (state) values('auditing');
insert into machine_state (state) values('rescue');
insert into machine_state (state) values('installing');
insert into machine_state (state) values('instantiating');
insert into machine_state (state) values('backing up');
insert into machine_state (state) values('rolling back');
insert into machine_state (state) values('updating');
insert into machine_substate (state) values('initial');
insert into machine_substate (state) values('executive');
insert into machine_substate (state) values('abortive');
insert into machine_substate (state) values('conclusive');
insert into machine_substate (state) values('failure');
insert into machine_substate (state) values('success');
insert into machine_substate (state) values('aborted');
insert into machine_substate (state) values('error');
insert into boot_device (name) values('cdrom');
insert into boot_device (name) values('floppy');
insert into boot_device (name) values('network');
insert into nic_driver (name) values('virtio-net');
insert into nic_driver (name) values('e100');
insert into nic_driver (name) values('e1000');
insert into nic_driver (name) values('rtl8139');
insert into nic_driver (name) values('physical');
create table guest_nic (id bigint unsigned not null auto_increment, guest_id bigint unsigned not null, nic_id bigint unsigned not null, primary key(id));
create table virtual_router_nic (id bigint unsigned not null auto_increment, virtual_router_id bigint unsigned not null, nic_id bigint unsigned not null, primary key(id));
create table hypervisor_server_nic (id bigint unsigned not null auto_increment, hypervisor_server_id bigint unsigned not null, nic_id bigint unsigned not null, primary key(id));
create table storage_server_nic (id bigint unsigned not null auto_increment, storage_server_id bigint unsigned not null, nic_id bigint unsigned not null, primary key(id));
create table guest_virtual_router (id bigint unsigned not null auto_increment, guest_id bigint unsigned not null, virtual_router_id bigint unsigned not null, primary key(id));
create table storage_server_disk (id bigint unsigned not null auto_increment, storage_server_id bigint unsigned not null, disk_id bigint unsigned not null, primary key(id));
create table hypervisor_server_disk (id bigint unsigned not null auto_increment, hypervisor_server_id bigint unsigned not null, disk_id bigint unsigned not null, primary key(id));
create table guest_vdisk (id bigint unsigned not null auto_increment, guest_id bigint unsigned not null, vdisk_id bigint unsigned not null, primary key(id));
create table virtual_router_vdisk (id bigint unsigned not null auto_increment, virtual_router_id bigint unsigned not null, vdisk_id bigint unsigned not null, primary key(id));
create table vdisk_snapshot (id bigint unsigned not null auto_increment, vdisk_id bigint unsigned not null, snapshot_id bigint unsigned not null, primary key(id));
create table guest_iso (id bigint unsigned not null auto_increment, guest_id bigint unsigned not null, iso_id bigint unsigned not null, primary key(id));
create table virtual_router_iso (id bigint unsigned not null auto_increment, virtual_router_id bigint unsigned not null, iso_id bigint unsigned not null, primary key(id));
create table guest_template (id bigint unsigned not null auto_increment, guest_id bigint unsigned not null, template_id bigint unsigned not null, primary key(id));
create table virtual_router_template (id bigint unsigned not null auto_increment, virtual_router_id bigint unsigned not null, template_id bigint unsigned not null, primary key(id));
create table guest_hypervisor_server (id bigint unsigned not null auto_increment, guest_id bigint unsigned not null, hypervisor_server_id bigint unsigned not null, primary key(id));
create table hypervisor_server (id bigint unsigned not null auto_increment, name varchar(64) not null, machine_state_id bigint unsigned not null, machine_substate_id bigint unsigned not null, cpu_capacity float(10,2) not null default 00000000.00, cpu_use float(5,2) not null default 000.00, ram_capacity float(10,2) not null default 00000000.00, ram_use float(5,2) not null default 000.00, primary key(id));
create table hypervisor_server_access_port_pool (id bigint unsigned not null, hypervisor_server_id bigint unsigned not null, acces_port_pool_id bigint unsigned not null, primary key(id));
create table storage_server (id bigint unsigned not null auto_increment, name varchar(64) not null, machine_state_id bigint unsigned not null, machine_substate_id bigint unsigned not null, cpu_capacity float(10,2) not null default 00000000.00, cpu_use float(5,2) not null default 000.00, ram_capacity float(10,2) not null default 00000000.00, ram_use float(5,2) not null default 000.00, volume_capacity float(10,2) not null default 00000000.00, volume_use float(5,2) not null default 000.00, primary key(id));
create table guest (id bigint unsigned not null auto_increment, name varchar(64) not null, machine_state_id bigint unsigned not null, machine_substate_id bigint unsigned not null, cpu_capacity float(10,2) not null default 00000000.00, cpu_use float(5,2) not null default 000.00, ram_capacity float(10,2) not null default 00000000.00, ram_use float(5,2) not null default 000.00, access_port_pool_id bigint unsigned not null, boot_device_id tinyint unsigned not null, primary key(id));
create table virtual_router (id bigint unsigned not null auto_increment, name varchar(64) not null, machine_state_id bigint unsigned not null, machine_substate_id bigint unsigned not null, cpu_capacity float(10,2) not null default 00000000.00, cpu_use float(5,2) not null default 000.00, ram_capacity float(10,2) not null default 00000000.00, ram_use float(5,2) not null default 000.00, acces_port_pool_id bigint unsigned not null, boot_device_id tinyint unsigned not null, virtual_router_id bigint unsigned null, network_name varchar(16) not null, primary key(id));
create table nic (id bigint unsigned not null auto_increment, ip_address_pool_id bigint unsigned not null, mac_address_pool_id bigint unsigned not null, vswitch_port_pool_id bigint unsigned not null, vlan_tag_pool_id bigint unsigned not null, nic_driver_id tinyint unsigned not null, primary key(id));
create table disk (id bigint unsigned not null auto_increment, capacity float(10,2) not null default 00000000.00, used float(10,2) not null default 00000000.00, primary key(id));
create table vdisk (id bigint unsigned not null auto_increment, capacity float(10,2) not null default 00000000.00, used float(10,2) not null default 00000000.00, primary_flag boolean not null default false, cow_flag boolean not null default false, primary key(id));
create table iso (id bigint unsigned not null auto_increment, name varchar(64) not null, boot_device_id tinyint unsigned not null default 0, nic_driver_id tinyint unsigned not null default 0, primary key(id));
create table template (id bigint unsigned not null auto_increment, name varchar(64) not null, iso_id bigint unsigned not null, vdisk_id bigint unsigned not null, primary key(id));
create table snapshot (id bigint unsigned not null auto_increment, name varchar(64) not null, snapshot_id bigint unsigned null, primary key(id));
create table ip_address_pool (id bigint unsigned not null auto_increment, name varchar(16) not null, taken_flag bool not null default 0, primary key(id));
create table mac_address_pool (id bigint unsigned not null auto_increment, name varchar(24) not null, taken_flag bool not null default 0, primary key(id));
create table vlan_tag_pool (id bigint unsigned not null auto_increment, name smallint unsigned not null, taken_flag bool not null default 0, primary key(id));
create table vswitch_port_pool (id bigint unsigned not null auto_increment, name smallint unsigned not null, taken_flag bool not null default 0, primary key(id));
create table access_port_pool (id bigint unsigned not null auto_increment, name smallint unsigned not null, taken_flag bool not null default 0, primary key(id));
create table settings (id bigint unsigned not null auto_increment, create_guest_from_template_default_machine_state_id tinyint unsigned not null, create_guest_from_template_default_machine_substate_id tinyint unsigned not null, create_guest_from_iso_default_machine_state_id tinyint unsigned not null, create_guest_from_iso_default_machine_substate_id tinyint unsigned not null, create_physical_default_machine_state_id tinyint unsigned not null, create_physical_default_machine_substate_id tinyint unsigned not null, guest_default_template_id bigint unsigned not null, guest_default_iso_id bigint unsigned not null, guest_default_virtual_router_id bigint unsigned not null, guest_default_vlan_id bigint unsigned not null, guest_default_nic_driver_id tinyint unsigned not null, guest_default_boot_device_id tinyint unsigned not null, guest_default_ram int unsigned not null, guest_default_ram_step int unsigned not null, guest_default_ram_max int unsigned not null, guest_default_ram_min int unsigned not null, guest_default_os_capacity int unsigned not null, guest_default_os_capacity_step int unsigned not null, guest_default_os_capacity_max int unsigned not null, guest_default_os_capacity_min int unsigned not null, guest_default_data_capacity int unsigned not null, guest_default_data_capacity_step int unsigned not null, guest_default_data_capacity_max int unsigned not null, guest_default_data_capacity_min int unsigned not null, physical_default_nic_driver_id tinyint unsigned not null, primary key(id));
insert into settings (create_guest_from_template_default_machine_state_id, create_guest_from_template_default_machine_substate_id, create_guest_from_iso_default_machine_state_id, create_guest_from_iso_default_machine_substate_id, create_physical_default_machine_state_id, create_physical_default_machine_substate_id, guest_default_template_id, guest_default_iso_id, guest_default_virtual_router_id, guest_default_vlan_id, guest_default_nic_driver_id, guest_default_boot_device_id, guest_default_ram, guest_default_ram_step, guest_default_ram_max, guest_default_ram_min, guest_default_os_capacity, guest_default_os_capacity_step, guest_default_os_capacity_max, guest_default_os_capacity_min, guest_default_data_capacity, guest_default_data_capacity_step, guest_default_data_capacity_max, guest_default_data_capacity_min, physical_default_nic_driver_id) values (13, 1, 1, 6, 1, 6, 1, 1, 1, 1, 1, 1, 512, 256, 16384, 256, 20, 20, 200, 20, 100, 100, 1000, 100, 5);
